---
title: "Project 6"
subtitle: "Request from a clinical dietitian"
bibliography: ref.bib
urlcolor: blue
---


::: callout-important
**Due date:** Monday, May 19 
:::

::: {.callout-note collapse="true"}
# Invite link for GitHub Classroom

Use the corresponding invite link in [this google doc](https://docs.google.com/document/d/12aVHO4med_qwvEkPE7KHtq1Tme0IVEXgEdLGZStvBco/edit?usp=sharing) (accessible with your EPFL account) to accept the project, and either join an existing team or create a new one.
:::

::: {.callout-warning collapse="true"}
# Submission requirements

You are required to hand in a PDF version of your report `report.pdf` (generated from the quarto file `report.qmd`, if applicable) and the quarto file itself. The `report.qmd` should contain all the code necessary to reproduce your results: you should not show the actual code in the PDF report, unless you want to point out something specific.

Your `README.md` should contain instructions on reproducing the PDF report from the quarto file. This can be useful if you have issues with the automatic generation of the PDF report right before the deadline.

An aternative to quarto (or Rmarkdown), is to use LaTeX to produce the report. In that case, you will also need to submit the source code where chunks should be well commented and references to the figures in the report should be clear.

**Checklist**:

1. [ ] `report.pdf` in GitHub repository (**max 15 pages**)
2. [ ]  Source code in GitHub repository 
3. [ ] `README.md` with instructions on how to run the code and reproduce the PDF report
:::

::: {.callout-note collapse="true"}
# Description of the Project

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

## Statement

A clinical dietitian wants to compare two different diets, $A$ and $B$, for diabetic patients

-   She hypothesizes that diet $A$ (Group 1) will be better than diet $B$ (Group 2), in terms of lower blood glucose
-   She plans to get a random sample of diabetic patients and randomly assign them to one of the two diets. At the end of the experiment, which lasts 6 weeks, a fasting blood glucose test will be conducted on each patient
-   She also expects that the average difference in blood glucose measure between the two groups will be about 10 mg/dl <!-- Furthermore, she also assumes the standard deviation of blood glucose distribution for diet A to be 15 and the standard deviation for diet B to be 17.   -->

The dietitian wants to know the number of subjects needed in each group assuming equal sized groups

## Project

**Tasks**:

-   Write a report answering the dietitian request, to the best of your ability
-   Keeping in mind that the dietitian has no background in statistics, please explain the most important technical terms, as well as the hypotheses on which you base your results
-   Do you have any recommendation as to how the experiment can be modified to improve the accuracy of the comparison? This is more of a conceptual point rather than a technical one

**Hints**: After a thorough research in the matter, we found out that

-   the standard deviation of blood glucose is typically around 15 mg/dl
-   clinical dietitians usually consider a significance level at $5\%$ and a power level at $80\%$
