---
title: "Tips + resources"
---

## General comments about Project 1

1. The report should be self-contained
   - it should not be a tutorial for the code (no variable names, file format, etc)
   - the reader should not have to jump between the report and the code to understand your work
2. Use the same verb tense throughout the report, unless you are mentioning others' work (then use the past tense)
3. Use already-implemented methods, when available 
4. When discussing your modelling/inference choices
   - clearly state your assumptions and your model(s)
   - write down the likelihood you are optimising (this is of course very specific to this project and you wouldn't need to do so in a project where the modelling assumptions directly apply to the data at hand)
   - in the MCMC part, clearly state your choices of priors and the likelihood
5. Briefly explain the statistical computational tools but no need to explain in details the visualization tools. Make sure though to understand what a histogram is (and other standard statistical notions)
6. If you produce multiple plots, of which one is better than the others, then restrict to the better one
7. Introduce abbreviations and notations


## Tips and tricks for visualisation

1. Consistency is the most important thing for a statistician.
   - jumping between different citation styles is bad
   - having some captions centered above the figure produced by R and others flushed right below using Markdown is annoying
2. Save space for better readability.
   - plots that convey little information don't have to be large, several (related) plots can be put next to each other on the same line, etc.
   - even in an `html` file, unnecessary scrolling back and forth when reading a report is annoying
   - a plot frame with one or two boxplots is a waste of space (e.g. histograms would be better)
   - barplots can often be replaced by tables to both save space and improve readability
   - in general, if a plot only shows like 3 numbers and is not important for any argument made, it should not be a plot
3. Story-telling matters.
   - it is important to grasp attention with an introduction (and describe at the same time what to expect from a report)
   - re-iterate the most important ideas/results in several places
   - comment on plots even if they are self-explanatory
4. More on plots.
   - text in figures (labels, etc.) should be of similar size as the main text
   - labels have to be readable, e.g. no overlaying etc.
   - captions are necessary and should make the plot self-contained (without looking at the paragraphs around it)
5. Less is sometimes more.
   - showing a scatterplot only to colors to it based on a group of two on the next plot, then adding one regression line, and then two regression lines on the fourth plot... just dilutes the important parts
   - Barplots colored by an additional variable should probably be replaced by a table (potentially colored by the cell
  values -- coloring for better readability only).
6. List of references should be itemized or enumerated (in order to be readable).
7. Avoid using local paths.
   - reproducibility of the report itself!
8. Transforming variables.
   - if your plots look bad because of a clear skewing in one of the variables, transform the varible (typically plot it on a log-scale)
   - if plotting on a log-scale, consider `log10` or `log2` to have better interpretability
  

