---
title: "Syllabus"
format: 
  html: default
  pdf: default
---

## Course description

The course will provide an overview of everyday challenges in applied statistics through case studies. Students will learn how to use core statistical methods and their extensions, and will use computational and problem-solving tools to provide reproducible solutions for the problems presented.

## Content

The course will be problem-based, but solutions to the problems may require ideas and tools from areas such as smoothing, regression analysis, statistical modelling (likelihood methods) and model selection, time series analysis, spatial and functional data analysis, extreme value analysis, and causal inference


## Prerequisites

Recommended courses: Regression methods, Statistical Computation and Visualisation.

## Learning Outcomes 
By the end of the course, the student must be able to:

- Propose suitable statistical solutions for real-world problems.
- Apply suitable statistical solutions for real-world problems.
- Assess / Evaluate the adequacy of a statistical method for a given task.
- Report results clearly in writing and orally to different types of stakeholder.


##  Transversal skills
- Give feedback (critique) in an appropriate fashion.
- Take feedback (critique) and respond in an appropriate manner.
- Communicate effectively with professionals from other disciplines.
- Identify the different roles that are involved in well-functioning teams and assume different roles, including leadership roles.
